plugins {
    id 'java'
    id 'maven-publish'
    id 'signing'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

def packageName = 'imgui-moulberry90-natives-linux'
def packageDesc = 'Native binaries for imgui.moulberry90 binding for Linux'
def moduleName = 'imgui.moulberry90.natives.linux'
def fromDir = '../bin'
def libName = 'libimgui-java64.so'

switch (findProperty('deployType')) {
    case 'windows':
        packageName = 'imgui-moulberry90-natives-windows'
        packageDesc = 'Native binaries for imgui.moulberry90 binding for Windows'
        moduleName = 'imgui.moulberry90.natives.windows'
        libName = 'imgui-java64.dll'
        break
    case 'linux':
        packageName = 'imgui-moulberry90-natives-linux'
        packageDesc = 'Native binaries for imgui.moulberry90 binding for Linux'
        moduleName = 'imgui.moulberry90.natives.linux'
        libName = 'libimgui-java64.so'
        break
    case 'macos':
        packageName = 'imgui-moulberry90-natives-macos'
        packageDesc = 'Native binaries for imgui.moulberry90 binding for macOS'
        moduleName = 'imgui.moulberry90.natives.macos'
        libName = 'libimgui-java64.dylib'
        break
}

jar {
    from(fromDir) {
        include "$libName" // this is fine
        into 'imgui/moulberry90/native-bin/'
    }
    manifest {
        attributes  'Automatic-Module-Name': moduleName
    }
}

apply from: "$rootDir/publish.gradle"
configurePublishing(packageName, packageDesc, project.version)
